
@url= http://localhost:3001

//Probamos las peticiones http a mi API con la extension Rest Client de VSC
GET {{url}}/products

###
GET {{url}}/products/1

###
POST {{url}}/products
Content-Type: application/json

{
    "name": "remeraAmarillaConLogo",
    "price": 1500,
    "stock": 100,
    "category": [Tshirts],
    "color": "yellow",
    "image": "https://blog.soyhenry.com/content/images/2021/05/LUCH.jpg"
}

###
DELETE {{url}}/products/1

###
PUT {{url}}/products/1