
@url= http://localhost:3001


GET {{url}}/products

###
GET {{url}}/products/63af64b85b6378162ac7cdde

###
POST {{url}}/products
Content-Type: application/json

{
    "name": "remera de Prueba",
    "price": 1500,
    "category": "Remeras",
    "color": "amarillo",
    "image": "https://blog.soyhenry.com/content/images/2021/05/LUCH.jpg"
}

###
DELETE {{url}}/products/1

###
PUT {{url}}/products/1